---
title: "Elections"
output: html_document
slug: elections
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 2016 United States of America Elections

#### We are analysing amount contributed towards campaigns of diffferent presidential candidates from California

```{r, message=FALSE,warning=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(lubridate)
library(fivethirtyeight)
library(here)
library(skimr)
library(janitor)
library(vroom)
library(tidyquant)
library(patchwork)
```


```{r, message=FALSE,warning=FALSE}

#using vroom to download a large sized file instead of the usual read_csv

CA_contributors_2016 <- vroom("CA_contributors_2016.csv")
glimpse(CA_contributors_2016)
```

```{r,message=FALSE,warning=FALSE}
zip_codes <- read_csv("zip_code_database.csv")

CA_contributors_2016$zip <- as.character(CA_contributors_2016$zip)
```

```{r,campagin}
#using inner join to get a dataframe containing information from both CA_contributors and zip csvs
campaign <- inner_join(CA_contributors_2016,zip_codes,by='zip')
glimpse(campaign)
```
```{r,message=FALSE,warning=FALSE}
#grouping by candidates to calculate the total aount received towards their campaigns

Total_contb <-campaign %>% 
  group_by(cand_nm) %>% 
  summarise(total_amt = sum(contb_receipt_amt)) %>% 
  arrange(desc(total_amt))
```

```{r,message=FALSE,warning=FALSE}

#Filtering the campaign by candidate, Hillary Clinton and state, California

Clinton_plot <- ggplot(filter(campaign,cand_nm=="Clinton, Hillary Rodham" & state == "CA") %>%  
               group_by(primary_city) %>% 
               summarise(total_amt_county = sum(contb_receipt_amt)) %>%
               arrange(desc(total_amt_county)) %>%
               slice_max(total_amt_county,n=10),aes(
                 x=total_amt_county,
                 y=reorder(primary_city,total_amt_county))) +
  geom_col(fill="red") + 
  labs(title = "Hillary Clinton") + 
  theme_clean() + 
  ylab(" ") + 
  xlab("Amount") + 
  scale_x_continuous(labels=scales::comma) +
  NULL
```

```{r,message=FALSE,warning=FALSE}


#Filtering the campaign by candidate, Donald Trump and state, California
Trump_plot <- ggplot(filter(campaign,cand_nm=="Trump, Donald J." & state == "CA") %>%  
                       group_by(primary_city) %>% 
                       summarise(total_amt_county = sum(contb_receipt_amt)) %>%
                       arrange(desc(total_amt_county)) %>%
                       slice_max(total_amt_county,n=10),aes(
                         x = total_amt_county,
                         y = reorder(primary_city,total_amt_county),)) +
  geom_col(fill= "blue") +
  labs(title="Donald Trump") +
  theme_clean() + ylab(" ") +
  xlab("Amount") +
  scale_x_continuous(labels = scales::comma) +
  NULL
```

```{r,fig.width=15}

#Joining two graphs together using patchwork
library(patchwork)

combined_plot <- Trump_plot +  
  Clinton_plot + 
  plot_annotation(title = "Where did the candidates raise most money?")

combined_plot
```

## Including Plots



```{r pressure,message=FALSE,warning=FALSE,fig.width=20,fig.height=15}
#Attempting to loop plots
library(patchwork)

#selecting top 10 rows from Total_contb
top_10_candidates <- Total_contb %>%
  slice_max(total_amt,n = 10)

plots <- list()

#creating a loop to run plots
Candidate_plots <- 1
for(politicians in top_10_candidates$cand_nm){
  plots[[Candidate_plots]] <- ggplot(filter(campaign,cand_nm == politicians & state == "CA") %>%  
                         group_by(primary_city) %>% 
                         summarise(total_amt_county = sum(contb_receipt_amt)) %>%
                         arrange(desc(total_amt_county)) %>%
                         slice_max(total_amt_county,n=10),aes(
                           x = total_amt_county,
                           y = reorder(primary_city,total_amt_county)
                           ))+
    geom_col(fill= "blue") +
    labs(title=politicians) +
    theme_clean() + 
    ylab(" ") +
    xlab("Amount") +
    scale_x_continuous(labels = scales::comma)
Candidate_plots <- Candidate_plots + 1
}

#wrapping plots together 
wrap_plots(plots,ncol =5)
```

